---
title: "Tarea Final"
author: "Estefanía Pineda Ortega"
date: "14/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introducción

Datos de flora, ORQUIDEAS. Nombre científico Orchidaceae) son una familia de plantas monocotiledóneas que se distinguen por la complejidad de sus flores.La familia comprende aproximadamente 25 000 especies.

## Carga de librerias 

```{r librerias, message=FALSE, warning=FALSE}

library(sf)
library(raster)
library(dplyr)
library(spData)
library(leaflet)
library(plotly)
library(DT)
library(tidyr)

```


## Carga de datos 
```{r Carga de datos, message=FALSE, warning=FALSE}

orq <-
  st_read(
    "https://raw.githubusercontent.com/gf0604-procesamientodatosgeograficos/2021i-datos/main/gbif/orchidaceae-cr-registros.csv",
    options = c(
      "X_POSSIBLE_NAMES=decimalLongitude",
      "Y_POSSIBLE_NAMES=decimalLatitude"
    ),
    quiet = TRUE
  )

asp <-
  st_read(
    "https://raw.githubusercontent.com/gf0604-procesamientodatosgeograficos/2021i-datos/main/sinac/asp/asp-wgs84.geojson",
    quiet = TRUE
  )

st_crs(asp) = 4326
st_crs(orq) = 4326

```


## Limpieza de datos 
```{r Limpieza, message=FALSE, warning=FALSE}

orq$species[orq$species == ""] <- "En blanco"

orq <- orq %>%
  filter(!is.na(coordinateUncertaintyInMeters) & coordinateUncertaintyInMeters <= 1000)%>%
  filter(species!="En blanco")

asp <- asp %>%
  filter(descripcio!="Area Marina de Manejo" & descripcio!="Area marina protegida")

```


## Carga de registros asp 
```{r registros asp, message=FALSE, warning=FALSE}

asp_registros <-
  asp %>%
  st_make_valid() %>%
  st_join(orq) %>%
  group_by(nombre_asp) %>%
  summarize(especies = n_distinct(species,na.rm = TRUE)) 

```

## Paleta de colores 
```{r Colores, message=FALSE, warning=FALSE}
# Paleta de colores
colores_registros <-
  colorNumeric(palette = "#9ecae1",
               domain = asp_registros$especies,
               na.color = "transparent")

# Paleta de colores
colores_especies <-
  colorNumeric(palette = "#f03b20",
               domain = asp_registros$especies,
               na.color = "transparent")

```


## Mapa 
```{r MAPA, message=FALSE, warning=FALSE}
# Mapa Leaflet

leaflet() %>%
  addTiles(group = "OSM") %>%
  addPolygons(
    data = asp_registros,
    fillColor = ~ colores_especies(asp_registros$especies),
    fillOpacity = 0.7,
    stroke = TRUE,
    color = "black",
    weight = 1,
    popup = paste(
      paste(
        "<strong>Provincia:</strong>",
        asp_registros$nombre_asp
      ),
      paste(
        "<strong>Cantidad de especies:</strong>",
        asp_registros$especies
        
      ),
      sep = '<br/>'
    ),
    group = "Provincias - especies"
  ) %>%
  addLayersControl(baseGroups = c("OSM"),
                   overlayGroups = c("Provincias - especies")) %>%
  addLegend(
    position = "bottomleft",
    pal = colores_especies,
    values = asp_registros$especies,
    group = "Provincias - especies",
    title = "Cantidad de orquideas")      

```


